# Generated by Django 5.1.4 on 2024-12-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_rename_description_candidate_manifesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=100, unique=True)),
                ('face_encoding', models.BinaryField()),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='voters/')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
        migrations.RemoveField(
            model_name='electionresult',
            name='election',
        ),
        migrations.RemoveField(
            model_name='electionresult',
            name='candidate',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='timestamp',
            new_name='vote_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='manifesto',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='party_logo',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='party_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default='default_image_path.jpg', upload_to='candidates/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(default='Independent', max_length=50),
        ),
        migrations.AddField(
            model_name='vote',
            name='encrypted_voter_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='ElectionResult',
        ),
    ]
